name: Test
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      xvfb:
        image: misoca/xvfb
        command: :1 -ac -listen tcp -screen 0 1600x1200x24
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm test
      env:
        DISPLAY: "xvfb:1.0"
