
name: Test
on: push
jobs:
  run:
    container: kipparker/docker-tape-run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: echo 'console.log(9001)' | browser-run
